### ISSUE TITLE
Diferenciar desde la API los casos exitosos de los no exitosos

### ISSUE THREAD

**Issue by matiasorieta** [ezebsas/parte-y-reparte#17]

**Comment by matiasorieta** [comment]
No entiendo a qué se refiere. Si un producto es cerrado pero no llega a alcanzar el mínimo de suscriptores, entonces queda en estado "INCOMPLETED", y si lo alcanza queda en estado "CLOSED"

**Comment by Alejo-Gurfein** [comment]
Capaz tener esos enum un poco mas descriptivo, tipo "CLOSED COMPLETED"? o capaz seria ponerle en el json q se devuelve un status: successful/failure?
